### ISSUE TITLE
release 1.0 build failed

### ISSUE THREAD

**Issue by marscher** [conda-forge/pytest-ignore-flaky-feedstock#5]
The new version is not available due to a failed build. It would be nice if the feedstock maintainer @rmcgibbo could trigger a rebuild. Thank you!

**Comment by rmcgibbo** [comment]
Alright, 1.0 is up.

**Comment by marscher** [comment]
Thanks!

Am 6. Mai 2019 21:00:47 MESZ schrieb "Robert T. McGibbon" <notifications@github.com>:
>Closed #5.
